# 他のプロジェクトで使用するサンプル
# このファイルを .github/workflows/tag-sbom-review.yml としてコピーしてください

name: Tag SBOM Review

on:
  push:
    tags:
      - 'v*'
      - 'release-*'

permissions:
  contents: read
  issues: write

jobs:
  sbom-review:
    uses: YOUR-ORG/log4j-vulnerable-sample/.github/workflows/reusable-tag-sbom-review.yml@main
    with:
      # オプション: カスタムライセンスガイドラインを使用する場合
      # license-guidelines-path: 'config/my-license-guidelines.yml'
      
      # オプション: Node.jsバージョンを指定する場合
      # node-version: '20'
    secrets:
      # Dependency-Track連携用（オプション）
      DT_BASE_URL: ${{ secrets.DT_BASE_URL }}
      DT_API_KEY: ${{ secrets.DT_API_KEY }}
      
      # GitHub token（必須）
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
