# 他のプロジェクトで使用するサンプル
# このファイルを .github/workflows/review-close.yml としてコピーしてください

name: Review Issue Close

on:
  issues:
    types: [closed]

permissions:
  contents: read
  issues: write

jobs:
  process-review:
    uses: YOUR-ORG/log4j-vulnerable-sample/.github/workflows/reusable-review-close.yml@main
    with:
      # オプション: Node.jsバージョンを指定する場合
      # node-version: '20'
    secrets:
      # GitHub token（必須）
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
